#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-nicoulaj-parent
Version  : 32
Release  : 2
URL      : https://github.com/nicoulaj/parent-pom/archive/32.tar.gz
Source0  : https://github.com/nicoulaj/parent-pom/archive/32.tar.gz
Source1  : https://repo.maven.apache.org/maven2/net/ju-n/net-ju-n-parent/32/net-ju-n-parent-32.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-nicoulaj-parent-data = %{version}-%{release}
Requires: mvn-nicoulaj-parent-license = %{version}-%{release}

%description
net.ju-n parent project
=======================
Parent POM for `net.ju-n` [projects](http://search.maven.org/#search%7Cga%7C1%7Cnet.ju-n).

%package data
Summary: data components for the mvn-nicoulaj-parent package.
Group: Data

%description data
data components for the mvn-nicoulaj-parent package.


%package license
Summary: license components for the mvn-nicoulaj-parent package.
Group: Default

%description license
license components for the mvn-nicoulaj-parent package.


%prep
%setup -q -n parent-pom-32

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-nicoulaj-parent
cp COPYING %{buildroot}/usr/share/package-licenses/mvn-nicoulaj-parent/COPYING
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/ju-n/net-ju-n-parent/32
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/ju-n/net-ju-n-parent/32/net-ju-n-parent-32.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/ju-n/net-ju-n-parent/32/net-ju-n-parent-32.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-nicoulaj-parent/COPYING
